platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
    tag: alpine
inputs:
  - name: source
  - name: infrastructure
outputs:
  - name: dockerfile
caches:
  - path: maven
run:
  path: infrastructure/concourse/app/build.sh