platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: alpine

inputs:
- name: source
- name: infra

outputs:
- name: dockerfile

caches:
- path: maven

run:
  path: ./infra/concourse/app/build.sh