jobs:
# Replace params / app_name with your heroku app name
- name: ci
  plan:
  - aggregate:
    - get: sw-api
      trigger: true
    - get: sw-api-infra
  - task: build_jar
    file: sw-api-infra/concourse/heroku/heroku_sync.yaml
    input_mapping: {source: sw-api, infra: sw-api-infra}
    params:
      OUTPUT_NAME: ((artifact_name))
  - task: deploy_jar
    file: sw-api-infra/concourse/heroku/heroku_deploy.yaml
    params:
      HEROKU_APP_NAME: ((heroku_app_name))-ci
      HEROKU_API_KEY: ((heroku_api_key))
      HEROKU_EMAIL: ((heroku_email))
      ARTIFACT_NAME: ((artifact_name))
- name: infra
  plan:
  - aggregate:
    - get: sw-api-infra
      trigger: true
  - task: apply
    file: sw-api-infra/concourse/terraform/task.yaml
    input_mapping: {source: sw-api-infra}
    params:
      github_token: ((github_token))
      heroku_api_key: ((heroku_api_key))
      heroku_email: ((heroku_email))
      command: apply
      directories: |
          terraform

#  The with-state is an output from the apply task. It's a git repo with
#  An updated terraform tfstate file.

  - put: sw-api-infra
    params:
      repository: with-state
      rebase: true

resources:

# Replace with your own repository
- name: sw-api
  type: git
  source:
      uri: git@github.com:kissorjeyabalan/sw-api.git
      branch: master
      private_key: ((deploy_app_ssh))

# Replace with your own repository
- name: sw-api-infra
  type: git
  source:
      uri: git@github.com:kissorjeyabalan/sw-api-infra.git
      branch: master
      private_key: ((deploy_infra_ssh))
